"""Verification tests for embedded C stack usage limits."""

import glob
import os
import subprocess

MAX_ALLOWED_STACK_BYTES = 2048


def test_compiler_stack_usage_budget():
    """Verify that all C functions compile within the embedded stack usage budget (<= 2048 bytes)."""
    build_res = subprocess.run(["make", "linux"], capture_output=True, text=True, check=False)
    assert build_res.returncode == 0, f"Build failed: {build_res.stderr}"

    su_files = glob.glob("*.su") + glob.glob("test/*.su")
    assert su_files, "No stack-usage (.su) files generated by GCC during build"

    violations = []
    analyzed_functions = {}

    for su_file in su_files:
        with open(su_file, "r") as f:
            for line in f:
                parts = line.strip().split("\t")
                if len(parts) >= 2:
                    func_loc = parts[0]
                    try:
                        stack_bytes = int(parts[1])
                    except ValueError:
                        continue

                    analyzed_functions[func_loc] = stack_bytes
                    if stack_bytes > MAX_ALLOWED_STACK_BYTES:
                        violations.append(f"{func_loc}: {stack_bytes} bytes (limit: {MAX_ALLOWED_STACK_BYTES})")

    assert not violations, "Stack usage budget exceeded for functions:\n" + "\n".join(violations)

    key_funcs = ["tshd_ls_dir", "tshd_execv"]
    for kf in key_funcs:
        found = any(kf in loc for loc in analyzed_functions)
        assert found, f"Expected function '{kf}' not found in stack usage report"
